#ifndef INC_CONSTANTS_SONAR_CONSTANTS_H_
#define INC_CONSTANTS_SONAR_CONSTANTS_H_


#define SONAR_LEFT_CHANNEL            	TIM_CHANNEL_3
#define SONAR_FRONT_CHANNEL 			TIM_CHANNEL_2
#define SONAR_RIGHT_CHANNEL 			TIM_CHANNEL_4


#endif /* INC_CONSTANTS_SONAR_CONSTANTS_H_ */
